//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkPara.Billing.Infrastructure.CorporationPaymentsService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelBase", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseModelBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseInstitutionList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillInquiry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillPayment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillCancel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillControl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseReconciliationSummary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseReconciliationDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestModelBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillInquiry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillPayment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillCancel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillControl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestReconciliationSummary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestReconciliationDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestInstitutionList))]
    public partial class ModelBase : object
    {
        
        private string EncryptedValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EncryptedValue
        {
            get
            {
                return this.EncryptedValueField;
            }
            set
            {
                this.EncryptedValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelBase", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseInstitutionList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillInquiry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillPayment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillCancel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillControl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseReconciliationSummary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseReconciliationDetail))]
    public partial class ResponseModelBase : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.Result[] ResultsField;
        
        private bool ShowMobilePopupField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.Result[] Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool ShowMobilePopup
        {
            get
            {
                return this.ShowMobilePopupField;
            }
            set
            {
                this.ShowMobilePopupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseInstitutionList", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class ResponseInstitutionList : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.InstitutionList[] InstitutionListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.InstitutionList[] InstitutionList
        {
            get
            {
                return this.InstitutionListField;
            }
            set
            {
                this.InstitutionListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBillInquiry", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class ResponseBillInquiry : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.BillList[] BillListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.BillList[] BillList
        {
            get
            {
                return this.BillListField;
            }
            set
            {
                this.BillListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBillPayment", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class ResponseBillPayment : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseModelBase
    {
        
        private decimal PaymentAccountAvailableBalanceField;
        
        private string PaymentAccountNumberField;
        
        private int PaymentIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PaymentAccountAvailableBalance
        {
            get
            {
                return this.PaymentAccountAvailableBalanceField;
            }
            set
            {
                this.PaymentAccountAvailableBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentAccountNumber
        {
            get
            {
                return this.PaymentAccountNumberField;
            }
            set
            {
                this.PaymentAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentId
        {
            get
            {
                return this.PaymentIdField;
            }
            set
            {
                this.PaymentIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBillCancel", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class ResponseBillCancel : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseModelBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBillControl", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class ResponseBillControl : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseModelBase
    {
        
        private bool CancelField;
        
        private int PaymentStatusField;
        
        private string StatusDescriptionField;
        
        private decimal TransactionReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cancel
        {
            get
            {
                return this.CancelField;
            }
            set
            {
                this.CancelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentStatus
        {
            get
            {
                return this.PaymentStatusField;
            }
            set
            {
                this.PaymentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription
        {
            get
            {
                return this.StatusDescriptionField;
            }
            set
            {
                this.StatusDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransactionReference
        {
            get
            {
                return this.TransactionReferenceField;
            }
            set
            {
                this.TransactionReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseReconciliationSummary", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class ResponseReconciliationSummary : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.InsReconciliationSummary[] InsReconciliationSummaryField;
        
        private System.DateTime ReconciliationDateField;
        
        private decimal TotalCancelAmountField;
        
        private int TotalCancelCountField;
        
        private decimal TotalPaymentAmountField;
        
        private int TotalPaymentCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.InsReconciliationSummary[] InsReconciliationSummary
        {
            get
            {
                return this.InsReconciliationSummaryField;
            }
            set
            {
                this.InsReconciliationSummaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReconciliationDate
        {
            get
            {
                return this.ReconciliationDateField;
            }
            set
            {
                this.ReconciliationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalCancelAmount
        {
            get
            {
                return this.TotalCancelAmountField;
            }
            set
            {
                this.TotalCancelAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCancelCount
        {
            get
            {
                return this.TotalCancelCountField;
            }
            set
            {
                this.TotalCancelCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPaymentAmount
        {
            get
            {
                return this.TotalPaymentAmountField;
            }
            set
            {
                this.TotalPaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPaymentCount
        {
            get
            {
                return this.TotalPaymentCountField;
            }
            set
            {
                this.TotalPaymentCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseReconciliationDetail", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class ResponseReconciliationDetail : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseModelBase
    {
        
        private System.DateTime ReconciliationDateField;
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.TransactionsPaymentEntity[] TransactionsPaymentEntityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReconciliationDate
        {
            get
            {
                return this.ReconciliationDateField;
            }
            set
            {
                this.ReconciliationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.TransactionsPaymentEntity[] TransactionsPaymentEntity
        {
            get
            {
                return this.TransactionsPaymentEntityField;
            }
            set
            {
                this.TransactionsPaymentEntityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestModelBase", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillInquiry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillPayment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillCancel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillControl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestReconciliationSummary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestReconciliationDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestInstitutionList))]
    public partial class RequestModelBase : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ModelBase
    {
        
        private string ExtUNameField;
        
        private string ExtUPasswordField;
        
        private string ExtUSessionKeyField;
        
        private bool IsNewDefinedTransactionField;
        
        private System.Nullable<int> LanguageIdField;
        
        private string MethodNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUName
        {
            get
            {
                return this.ExtUNameField;
            }
            set
            {
                this.ExtUNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUPassword
        {
            get
            {
                return this.ExtUPasswordField;
            }
            set
            {
                this.ExtUPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUSessionKey
        {
            get
            {
                return this.ExtUSessionKeyField;
            }
            set
            {
                this.ExtUSessionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsNewDefinedTransaction
        {
            get
            {
                return this.IsNewDefinedTransactionField;
            }
            set
            {
                this.IsNewDefinedTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> LanguageId
        {
            get
            {
                return this.LanguageIdField;
            }
            set
            {
                this.LanguageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBillInquiry", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class RequestBillInquiry : LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContextField;
        
        private string FirstQueryFieldField;
        
        private int InstitutionIdField;
        
        private string SecondQueryFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContext
        {
            get
            {
                return this.CorporationSecurityContextField;
            }
            set
            {
                this.CorporationSecurityContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FirstQueryField
        {
            get
            {
                return this.FirstQueryFieldField;
            }
            set
            {
                this.FirstQueryFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int InstitutionId
        {
            get
            {
                return this.InstitutionIdField;
            }
            set
            {
                this.InstitutionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondQueryField
        {
            get
            {
                return this.SecondQueryFieldField;
            }
            set
            {
                this.SecondQueryFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBillPayment", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class RequestBillPayment : LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.BillList[] BillListField;
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContextField;
        
        private string PayerNameField;
        
        private string PayerPhoneField;
        
        private string PayerTaxNumberField;
        
        private int TransactionGuidIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.BillList[] BillList
        {
            get
            {
                return this.BillListField;
            }
            set
            {
                this.BillListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContext
        {
            get
            {
                return this.CorporationSecurityContextField;
            }
            set
            {
                this.CorporationSecurityContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PayerName
        {
            get
            {
                return this.PayerNameField;
            }
            set
            {
                this.PayerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PayerPhone
        {
            get
            {
                return this.PayerPhoneField;
            }
            set
            {
                this.PayerPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PayerTaxNumber
        {
            get
            {
                return this.PayerTaxNumberField;
            }
            set
            {
                this.PayerTaxNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TransactionGuidId
        {
            get
            {
                return this.TransactionGuidIdField;
            }
            set
            {
                this.TransactionGuidIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBillCancel", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class RequestBillCancel : LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContextField;
        
        private int TransactionGuidIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContext
        {
            get
            {
                return this.CorporationSecurityContextField;
            }
            set
            {
                this.CorporationSecurityContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TransactionGuidId
        {
            get
            {
                return this.TransactionGuidIdField;
            }
            set
            {
                this.TransactionGuidIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBillControl", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class RequestBillControl : LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContextField;
        
        private int TransactionGuidIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContext
        {
            get
            {
                return this.CorporationSecurityContextField;
            }
            set
            {
                this.CorporationSecurityContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TransactionGuidId
        {
            get
            {
                return this.TransactionGuidIdField;
            }
            set
            {
                this.TransactionGuidIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestReconciliationSummary", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class RequestReconciliationSummary : LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContextField;
        
        private bool GroupByInstitutionField;
        
        private System.Nullable<int> InstitutionIdField;
        
        private System.DateTime ReconciliationDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContext
        {
            get
            {
                return this.CorporationSecurityContextField;
            }
            set
            {
                this.CorporationSecurityContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GroupByInstitution
        {
            get
            {
                return this.GroupByInstitutionField;
            }
            set
            {
                this.GroupByInstitutionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InstitutionId
        {
            get
            {
                return this.InstitutionIdField;
            }
            set
            {
                this.InstitutionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ReconciliationDate
        {
            get
            {
                return this.ReconciliationDateField;
            }
            set
            {
                this.ReconciliationDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestReconciliationDetail", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class RequestReconciliationDetail : LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContextField;
        
        private bool GetOnlyFaultyTransactionsField;
        
        private System.Nullable<int> InstitutionIdField;
        
        private System.DateTime ReconciliationDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContext
        {
            get
            {
                return this.CorporationSecurityContextField;
            }
            set
            {
                this.CorporationSecurityContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool GetOnlyFaultyTransactions
        {
            get
            {
                return this.GetOnlyFaultyTransactionsField;
            }
            set
            {
                this.GetOnlyFaultyTransactionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InstitutionId
        {
            get
            {
                return this.InstitutionIdField;
            }
            set
            {
                this.InstitutionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ReconciliationDate
        {
            get
            {
                return this.ReconciliationDateField;
            }
            set
            {
                this.ReconciliationDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInstitutionList", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class RequestInstitutionList : LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestModelBase
    {
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.CorporationSecurityContext CorporationSecurityContext
        {
            get
            {
                return this.CorporationSecurityContextField;
            }
            set
            {
                this.CorporationSecurityContextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorporationSecurityContext", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class CorporationSecurityContext : object
    {
        
        private string OrganizationBranchCodeField;
        
        private string OrganizationBranchUserCodeField;
        
        private int OrganizationIdField;
        
        private string OrganizationPasswordField;
        
        private string ServicePasswordField;
        
        private string ServiceUserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationBranchCode
        {
            get
            {
                return this.OrganizationBranchCodeField;
            }
            set
            {
                this.OrganizationBranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationBranchUserCode
        {
            get
            {
                return this.OrganizationBranchUserCodeField;
            }
            set
            {
                this.OrganizationBranchUserCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrganizationId
        {
            get
            {
                return this.OrganizationIdField;
            }
            set
            {
                this.OrganizationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrganizationPassword
        {
            get
            {
                return this.OrganizationPasswordField;
            }
            set
            {
                this.OrganizationPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ServicePassword
        {
            get
            {
                return this.ServicePasswordField;
            }
            set
            {
                this.ServicePasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ServiceUserName
        {
            get
            {
                return this.ServiceUserNameField;
            }
            set
            {
                this.ServiceUserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public partial class Result : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExceptionField;
        
        private bool IsFriendlyField;
        
        private string[] ParamsField;
        
        private LinkPara.Billing.Infrastructure.CorporationPaymentsService.Severity SeverityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsFriendly
        {
            get
            {
                return this.IsFriendlyField;
            }
            set
            {
                this.IsFriendlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Params
        {
            get
            {
                return this.ParamsField;
            }
            set
            {
                this.ParamsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public LinkPara.Billing.Infrastructure.CorporationPaymentsService.Severity Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Severity", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public enum Severity : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstitutionList", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class InstitutionList : object
    {
        
        private string AdditionalInfoInputFieldField;
        
        private int AdditionalInfoInputFieldMaxLengthField;
        
        private int InstitutionIdField;
        
        private string InstitutionLongNameField;
        
        private string InstitutionShortNameField;
        
        private int InstitutionTypeField;
        
        private bool IsAllowsPartialPaymentField;
        
        private bool IsAllowsPaymentField;
        
        private bool IsAllowsQueryField;
        
        private bool IsOnlineField;
        
        private bool IsRequiredAdditionalInfoInputFieldField;
        
        private bool IsSubscriberNoNumericField;
        
        private string SubscriberLabelField;
        
        private string SubscriberNoHelpTextField;
        
        private int SubscriberNoMaxLengthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfoInputField
        {
            get
            {
                return this.AdditionalInfoInputFieldField;
            }
            set
            {
                this.AdditionalInfoInputFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdditionalInfoInputFieldMaxLength
        {
            get
            {
                return this.AdditionalInfoInputFieldMaxLengthField;
            }
            set
            {
                this.AdditionalInfoInputFieldMaxLengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstitutionId
        {
            get
            {
                return this.InstitutionIdField;
            }
            set
            {
                this.InstitutionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitutionLongName
        {
            get
            {
                return this.InstitutionLongNameField;
            }
            set
            {
                this.InstitutionLongNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitutionShortName
        {
            get
            {
                return this.InstitutionShortNameField;
            }
            set
            {
                this.InstitutionShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstitutionType
        {
            get
            {
                return this.InstitutionTypeField;
            }
            set
            {
                this.InstitutionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAllowsPartialPayment
        {
            get
            {
                return this.IsAllowsPartialPaymentField;
            }
            set
            {
                this.IsAllowsPartialPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAllowsPayment
        {
            get
            {
                return this.IsAllowsPaymentField;
            }
            set
            {
                this.IsAllowsPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAllowsQuery
        {
            get
            {
                return this.IsAllowsQueryField;
            }
            set
            {
                this.IsAllowsQueryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline
        {
            get
            {
                return this.IsOnlineField;
            }
            set
            {
                this.IsOnlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequiredAdditionalInfoInputField
        {
            get
            {
                return this.IsRequiredAdditionalInfoInputFieldField;
            }
            set
            {
                this.IsRequiredAdditionalInfoInputFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSubscriberNoNumeric
        {
            get
            {
                return this.IsSubscriberNoNumericField;
            }
            set
            {
                this.IsSubscriberNoNumericField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberLabel
        {
            get
            {
                return this.SubscriberLabelField;
            }
            set
            {
                this.SubscriberLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberNoHelpText
        {
            get
            {
                return this.SubscriberNoHelpTextField;
            }
            set
            {
                this.SubscriberNoHelpTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubscriberNoMaxLength
        {
            get
            {
                return this.SubscriberNoMaxLengthField;
            }
            set
            {
                this.SubscriberNoMaxLengthField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillList", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class BillList : object
    {
        
        private string AdditionalInfoField;
        
        private System.Nullable<decimal> AmountField;
        
        private string BillNumberField;
        
        private System.Nullable<decimal> DebtAmountField;
        
        private string DebtExtensionField;
        
        private System.Nullable<int> DebtIdField;
        
        private string DebtInfoField;
        
        private string DebtProcessTypeField;
        
        private string DescriptionField;
        
        private System.Nullable<int> InstitutionIdField;
        
        private System.Nullable<System.DateTime> InvoiceDateField;
        
        private System.Nullable<decimal> InvoiceDelayAmountField;
        
        private System.Nullable<System.DateTime> LastPaymenDateField;
        
        private string NameSurnameField;
        
        private string PeriodField;
        
        private System.Nullable<int> PriorityField;
        
        private string ReferenceNumberField;
        
        private string SecondQueryFieldField;
        
        private string SubscriberNumberField;
        
        private string YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo
        {
            get
            {
                return this.AdditionalInfoField;
            }
            set
            {
                this.AdditionalInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNumber
        {
            get
            {
                return this.BillNumberField;
            }
            set
            {
                this.BillNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> DebtAmount
        {
            get
            {
                return this.DebtAmountField;
            }
            set
            {
                this.DebtAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebtExtension
        {
            get
            {
                return this.DebtExtensionField;
            }
            set
            {
                this.DebtExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> DebtId
        {
            get
            {
                return this.DebtIdField;
            }
            set
            {
                this.DebtIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebtInfo
        {
            get
            {
                return this.DebtInfoField;
            }
            set
            {
                this.DebtInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebtProcessType
        {
            get
            {
                return this.DebtProcessTypeField;
            }
            set
            {
                this.DebtProcessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> InstitutionId
        {
            get
            {
                return this.InstitutionIdField;
            }
            set
            {
                this.InstitutionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InvoiceDate
        {
            get
            {
                return this.InvoiceDateField;
            }
            set
            {
                this.InvoiceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InvoiceDelayAmount
        {
            get
            {
                return this.InvoiceDelayAmountField;
            }
            set
            {
                this.InvoiceDelayAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> LastPaymenDate
        {
            get
            {
                return this.LastPaymenDateField;
            }
            set
            {
                this.LastPaymenDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NameSurname
        {
            get
            {
                return this.NameSurnameField;
            }
            set
            {
                this.NameSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Period
        {
            get
            {
                return this.PeriodField;
            }
            set
            {
                this.PeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondQueryField
        {
            get
            {
                return this.SecondQueryFieldField;
            }
            set
            {
                this.SecondQueryFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SubscriberNumber
        {
            get
            {
                return this.SubscriberNumberField;
            }
            set
            {
                this.SubscriberNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsReconciliationSummary", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class InsReconciliationSummary : object
    {
        
        private decimal InsTotalCancelAmountField;
        
        private int InsTotalCancelCountField;
        
        private decimal InsTotalPaymentAmountField;
        
        private int InsTotalPaymentCountField;
        
        private System.Nullable<int> InstitutionIdField;
        
        private string InstitutionNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InsTotalCancelAmount
        {
            get
            {
                return this.InsTotalCancelAmountField;
            }
            set
            {
                this.InsTotalCancelAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InsTotalCancelCount
        {
            get
            {
                return this.InsTotalCancelCountField;
            }
            set
            {
                this.InsTotalCancelCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InsTotalPaymentAmount
        {
            get
            {
                return this.InsTotalPaymentAmountField;
            }
            set
            {
                this.InsTotalPaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InsTotalPaymentCount
        {
            get
            {
                return this.InsTotalPaymentCountField;
            }
            set
            {
                this.InsTotalPaymentCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InstitutionId
        {
            get
            {
                return this.InstitutionIdField;
            }
            set
            {
                this.InstitutionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitutionName
        {
            get
            {
                return this.InstitutionNameField;
            }
            set
            {
                this.InstitutionNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionsPaymentEntity", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CollectionManagemen" +
        "t")]
    public partial class TransactionsPaymentEntity : object
    {
        
        private string BillNoField;
        
        private System.Nullable<int> InstitutionIdField;
        
        private bool IsCancelledField;
        
        private decimal PaymentAmountField;
        
        private int PaymentCustomerIdField;
        
        private int PaymentExtensionIdField;
        
        private int PaymentIdField;
        
        private string SubscriberIdField;
        
        private string SubscriberNameField;
        
        private System.DateTime TransactionDateField;
        
        private int TransactionIdField;
        
        private string VendorTerminalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNo
        {
            get
            {
                return this.BillNoField;
            }
            set
            {
                this.BillNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InstitutionId
        {
            get
            {
                return this.InstitutionIdField;
            }
            set
            {
                this.InstitutionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCancelled
        {
            get
            {
                return this.IsCancelledField;
            }
            set
            {
                this.IsCancelledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PaymentAmount
        {
            get
            {
                return this.PaymentAmountField;
            }
            set
            {
                this.PaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentCustomerId
        {
            get
            {
                return this.PaymentCustomerIdField;
            }
            set
            {
                this.PaymentCustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentExtensionId
        {
            get
            {
                return this.PaymentExtensionIdField;
            }
            set
            {
                this.PaymentExtensionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentId
        {
            get
            {
                return this.PaymentIdField;
            }
            set
            {
                this.PaymentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberId
        {
            get
            {
                return this.SubscriberIdField;
            }
            set
            {
                this.SubscriberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberName
        {
            get
            {
                return this.SubscriberNameField;
            }
            set
            {
                this.SubscriberNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate
        {
            get
            {
                return this.TransactionDateField;
            }
            set
            {
                this.TransactionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorTerminal
        {
            get
            {
                return this.VendorTerminalField;
            }
            set
            {
                this.VendorTerminalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://boa.net/BOA.Integration.CollectionManagement/Service", ConfigurationName="LinkPara.Billing.Infrastructure.CorporationPaymentsService.ICorporationPaymentsSe" +
        "rvice")]
    public interface ICorporationPaymentsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/GetCorporations", ReplyAction="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/GetCorporationsResponse")]
        System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseInstitutionList> GetCorporationsAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestInstitutionList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/GetDebt", ReplyAction="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/GetDebtResponse")]
        System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillInquiry> GetDebtAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillInquiry request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/DoPayment", ReplyAction="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/DoPaymentResponse")]
        System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillPayment> DoPaymentAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillPayment request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/CancelPayment", ReplyAction="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/CancelPaymentResponse")]
        System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillCancel> CancelPaymentAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillCancel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/ControlPayment", ReplyAction="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/ControlPaymentResponse")]
        System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillControl> ControlPaymentAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillControl request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/ReconciliationSummary", ReplyAction="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/ReconciliationSummaryResponse")]
        System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseReconciliationSummary> ReconciliationSummaryAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestReconciliationSummary request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/ReconciliationSummaryDetail", ReplyAction="http://boa.net/BOA.Integration.CollectionManagement/Service/ICorporationPaymentsS" +
            "ervice/ReconciliationSummaryDetailResponse")]
        System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseReconciliationDetail> ReconciliationSummaryDetailAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestReconciliationDetail request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ICorporationPaymentsServiceChannel : LinkPara.Billing.Infrastructure.CorporationPaymentsService.ICorporationPaymentsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CorporationPaymentsServiceClient : System.ServiceModel.ClientBase<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ICorporationPaymentsService>, LinkPara.Billing.Infrastructure.CorporationPaymentsService.ICorporationPaymentsService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CorporationPaymentsServiceClient() : 
                base(CorporationPaymentsServiceClient.GetDefaultBinding(), CorporationPaymentsServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICorporationPaymentsService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporationPaymentsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CorporationPaymentsServiceClient.GetBindingForEndpoint(endpointConfiguration), CorporationPaymentsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporationPaymentsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CorporationPaymentsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporationPaymentsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CorporationPaymentsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporationPaymentsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseInstitutionList> GetCorporationsAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestInstitutionList request)
        {
            return base.Channel.GetCorporationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillInquiry> GetDebtAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillInquiry request)
        {
            return base.Channel.GetDebtAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillPayment> DoPaymentAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillPayment request)
        {
            return base.Channel.DoPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillCancel> CancelPaymentAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillCancel request)
        {
            return base.Channel.CancelPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseBillControl> ControlPaymentAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestBillControl request)
        {
            return base.Channel.ControlPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseReconciliationSummary> ReconciliationSummaryAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestReconciliationSummary request)
        {
            return base.Channel.ReconciliationSummaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<LinkPara.Billing.Infrastructure.CorporationPaymentsService.ResponseReconciliationDetail> ReconciliationSummaryDetailAsync(LinkPara.Billing.Infrastructure.CorporationPaymentsService.RequestReconciliationDetail request)
        {
            return base.Channel.ReconciliationSummaryDetailAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICorporationPaymentsService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICorporationPaymentsService))
            {
                return new System.ServiceModel.EndpointAddress("https://boatest.vakifkatilim.com.tr/BOA.Integration.WCFServiceTest/BOA.Integratio" +
                        "n.CollectionManagement/CorporationPaymentsService.svc/Basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CorporationPaymentsServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICorporationPaymentsService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CorporationPaymentsServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICorporationPaymentsService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICorporationPaymentsService,
        }
    }
}
