IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'CustomerWalletCard' AND COLUMN_NAME = 'CardStatus'
)
BEGIN
    ALTER TABLE Core.[CustomerWalletCard] ADD CardStatus;
END
GO

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'CustomerWalletCard' AND COLUMN_NAME = 'UserId'
)
BEGIN
    ALTER TABLE Core.[CustomerWalletCard] DROP COLUMN UserId;
END
GO