IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'CustomerWalletCard' AND COLUMN_NAME = 'CardName'
)
BEGIN
    ALTER TABLE Core.[CustomerWalletCard] ADD CardName NVARCHAR(30);
END
GO
