IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Merchant'
        AND TABLE_NAME = 'Pool'
        AND COLUMN_NAME = 'PosType'
)
BEGIN
ALTER TABLE Merchant.Pool ADD PosType VARCHAR(50) NOT NULL DEFAULT 'Virtual';
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Merchant'
        AND TABLE_NAME = 'Merchant'
        AND COLUMN_NAME = 'PosType'
)
BEGIN
ALTER TABLE Merchant.Merchant ADD PosType VARCHAR(50) NOT NULL DEFAULT 'Virtual';
END