using LinkPara.Card.Domain.Entities.FileIngestion.Persistence;
using LinkPara.Card.Domain.Entities.FileIngestion.Schemas;

namespace LinkPara.Card.Infrastructure.Services.FileIngestion.Parsing;

public class IngestionDetailEntityMapper : IIngestionDetailEntityMapper
{
    public void AttachTypedDetail(IngestionFileLine row, string profileKey, object parsedDataModel)
    {
        if (!string.Equals(row.RecordType, "D", StringComparison.OrdinalIgnoreCase))
            return;

        switch (profileKey)
        {
            case "CardVisa" when parsedDataModel is CardVisaDetail cvd:
                row.CardVisaDetail = MapCardVisaDetail(cvd);
                break;
            case "CardMsc" when parsedDataModel is CardMscDetail cmd:
                row.CardMscDetail = MapCardMscDetail(cmd);
                break;
            case "CardBkm" when parsedDataModel is CardBkmDetail cbd:
                row.CardBkmDetail = MapCardBkmDetail(cbd);
                break;
            case "ClearingVisa" when parsedDataModel is ClearingVisaDetail clvd:
                row.ClearingVisaDetail = MapClearingVisaDetail(clvd);
                break;
            case "ClearingMsc" when parsedDataModel is ClearingMscDetail clmd:
                row.ClearingMscDetail = MapClearingMscDetail(clmd);
                break;
            case "ClearingBkm" when parsedDataModel is ClearingBkmDetail clbd:
                row.ClearingBkmDetail = MapClearingBkmDetail(clbd);
                break;
        }
    }

    private static IngestionCardVisaDetail MapCardVisaDetail(CardVisaDetail s) => new()
    {
        TransactionDate = s.TransactionDate,
        TransactionTime = s.TransactionTime,
        ValueDate = s.ValueDate,
        EndOfDayDate = s.EndOfDayDate,
        CardNo = s.CardNo,
        OceanTxnGuid = s.OceanTxnGuid,
        OceanMainTxnGuid = s.OceanMainTxnGuid,
        BranchId = s.BranchId,
        Rrn = s.Rrn,
        Arn = s.Arn,
        ProvisionCode = s.ProvisionCode,
        Stan = s.Stan,
        MemberRefNo = s.MemberRefNo,
        TraceId = s.TraceId,
        Otc = s.Otc,
        Ots = s.Ots,
        TxnInstallType = s.TxnInstallType,
        BankingTxnCode = s.BankingTxnCode,
        TxnDescription = s.TxnDescription,
        MerchantName = s.MerchantName,
        MerchantCity = s.MerchantCity,
        MerchantState = s.MerchantState,
        MerchantCountry = s.MerchantCountry,
        FinancialType = s.FinancialType,
        TxnEffect = s.TxnEffect,
        TxnSource = s.TxnSource,
        TxnRegion = s.TxnRegion,
        TerminalType = s.TerminalType,
        ChannelCode = s.ChannelCode,
        TerminalId = s.TerminalId,
        MerchantId = s.MerchantId,
        Mcc = s.Mcc,
        AcquirerId = s.AcquirerId,
        SecurityLevelIndicator = s.SecurityLevelIndicator,
        IsTxnSettle = s.IsTxnSettle,
        TxnStat = s.TxnStat,
        ResponseCode = s.ResponseCode,
        IsSuccessfulTxn = s.IsSuccessfulTxn,
        TxnOrigin = s.TxnOrigin,
        InstallCount = s.InstallCount,
        InstallOrder = s.InstallOrder,
        OperatorCode = s.OperatorCode,
        OriginalAmount = s.OriginalAmount,
        OriginalCurrency = s.OriginalCurrency,
        SettlementAmount = s.SettlementAmount,
        SettlementCurrency = s.SettlementCurrency,
        CardHolderBillingAmount = s.CardHolderBillingAmount,
        CardHolderBillingCurrency = s.CardHolderBillingCurrency,
        BillingAmount = s.BillingAmount,
        BillingCurrency = s.BillingCurrency,
        Tax1 = s.Tax1,
        Tax2 = s.Tax2,
        CashbackAmount = s.CashbackAmount,
        SurchargeAmount = s.SurchargeAmount,
        PointType = s.PointType,
        BcPoint = s.BcPoint,
        McPoint = s.McPoint,
        CcPoint = s.CcPoint,
        BcPointAmount = s.BcPointAmount,
        McPointAmount = s.McPointAmount,
        CcPointAmount = s.CcPointAmount
    };

    private static IngestionCardMscDetail MapCardMscDetail(CardMscDetail s) => new()
    {
        TransactionDate = s.TransactionDate,
        TransactionTime = s.TransactionTime,
        ValueDate = s.ValueDate,
        EndOfDayDate = s.EndOfDayDate,
        CardNo = s.CardNo,
        OceanTxnGuid = s.OceanTxnGuid,
        OceanMainTxnGuid = s.OceanMainTxnGuid,
        BranchId = s.BranchId,
        Rrn = s.Rrn,
        Arn = s.Arn,
        ProvisionCode = s.ProvisionCode,
        Stan = s.Stan,
        MemberRefNo = s.MemberRefNo,
        TraceId = s.TraceId,
        Otc = s.Otc,
        Ots = s.Ots,
        TxnInstallType = s.TxnInstallType,
        BankingTxnCode = s.BankingTxnCode,
        TxnDescription = s.TxnDescription,
        MerchantName = s.MerchantName,
        MerchantCity = s.MerchantCity,
        MerchantState = s.MerchantState,
        MerchantCountry = s.MerchantCountry,
        FinancialType = s.FinancialType,
        TxnEffect = s.TxnEffect,
        TxnSource = s.TxnSource,
        TxnRegion = s.TxnRegion,
        TerminalType = s.TerminalType,
        ChannelCode = s.ChannelCode,
        TerminalId = s.TerminalId,
        MerchantId = s.MerchantId,
        Mcc = s.Mcc,
        AcquirerId = s.AcquirerId,
        SecurityLevelIndicator = s.SecurityLevelIndicator,
        IsTxnSettle = s.IsTxnSettle,
        TxnStat = s.TxnStat,
        ResponseCode = s.ResponseCode,
        IsSuccessfulTxn = s.IsSuccessfulTxn,
        TxnOrigin = s.TxnOrigin,
        InstallCount = s.InstallCount,
        InstallOrder = s.InstallOrder,
        OperatorCode = s.OperatorCode,
        OriginalAmount = s.OriginalAmount,
        OriginalCurrency = s.OriginalCurrency,
        SettlementAmount = s.SettlementAmount,
        SettlementCurrency = s.SettlementCurrency,
        CardHolderBillingAmount = s.CardHolderBillingAmount,
        CardHolderBillingCurrency = s.CardHolderBillingCurrency,
        BillingAmount = s.BillingAmount,
        BillingCurrency = s.BillingCurrency,
        Tax1 = s.Tax1,
        Tax2 = s.Tax2,
        CashbackAmount = s.CashbackAmount,
        SurchargeAmount = s.SurchargeAmount,
        PointType = s.PointType,
        BcPoint = s.BcPoint,
        McPoint = s.McPoint,
        CcPoint = s.CcPoint,
        BcPointAmount = s.BcPointAmount,
        McPointAmount = s.McPointAmount,
        CcPointAmount = s.CcPointAmount
    };

    private static IngestionCardBkmDetail MapCardBkmDetail(CardBkmDetail s) => new()
    {
        TransactionDate = s.TransactionDate,
        TransactionTime = s.TransactionTime,
        ValueDate = s.ValueDate,
        EndOfDayDate = s.EndOfDayDate,
        CardNo = s.CardNo,
        OceanTxnGuid = s.OceanTxnGuid,
        OceanMainTxnGuid = s.OceanMainTxnGuid,
        BranchId = s.BranchId,
        Rrn = s.Rrn,
        Arn = s.Arn,
        ProvisionCode = s.ProvisionCode,
        Stan = s.Stan,
        MemberRefNo = s.MemberRefNo,
        TraceId = s.TraceId,
        Otc = s.Otc,
        Ots = s.Ots,
        TxnInstallType = s.TxnInstallType,
        BankingTxnCode = s.BankingTxnCode,
        TxnDescription = s.TxnDescription,
        MerchantName = s.MerchantName,
        MerchantCity = s.MerchantCity,
        MerchantState = s.MerchantState,
        MerchantCountry = s.MerchantCountry,
        FinancialType = s.FinancialType,
        TxnEffect = s.TxnEffect,
        TxnSource = s.TxnSource,
        TxnRegion = s.TxnRegion,
        TerminalType = s.TerminalType,
        ChannelCode = s.ChannelCode,
        TerminalId = s.TerminalId,
        MerchantId = s.MerchantId,
        Mcc = s.Mcc,
        AcquirerId = s.AcquirerId,
        SecurityLevelIndicator = s.SecurityLevelIndicator,
        IsTxnSettle = s.IsTxnSettle,
        TxnStat = s.TxnStat,
        ResponseCode = s.ResponseCode,
        IsSuccessfulTxn = s.IsSuccessfulTxn,
        TxnOrigin = s.TxnOrigin,
        InstallCount = s.InstallCount,
        InstallOrder = s.InstallOrder,
        OperatorCode = s.OperatorCode,
        OriginalAmount = s.OriginalAmount,
        OriginalCurrency = s.OriginalCurrency,
        SettlementAmount = s.SettlementAmount,
        SettlementCurrency = s.SettlementCurrency,
        CardHolderBillingAmount = s.CardHolderBillingAmount,
        CardHolderBillingCurrency = s.CardHolderBillingCurrency,
        BillingAmount = s.BillingAmount,
        BillingCurrency = s.BillingCurrency,
        Tax1 = s.Tax1,
        Tax2 = s.Tax2,
        CashbackAmount = s.CashbackAmount,
        SurchargeAmount = s.SurchargeAmount,
        PointType = s.PointType,
        BcPoint = s.BcPoint,
        McPoint = s.McPoint,
        CcPoint = s.CcPoint,
        BcPointAmount = s.BcPointAmount,
        McPointAmount = s.McPointAmount,
        CcPointAmount = s.CcPointAmount
    };

    private static IngestionClearingVisaDetail MapClearingVisaDetail(ClearingVisaDetail s) => new()
    {
        TxnType = s.TxnType,
        IoDate = s.IoDate,
        IoFlag = s.IoFlag,
        OceanTxnGuid = s.OceanTxnGuid,
        ClrNo = s.ClrNo,
        Rrn = s.Rrn,
        Arn = s.Arn,
        ReasonCode = s.ReasonCode,
        Reserved = s.Reserved,
        ProvisionCode = s.ProvisionCode,
        CardNo = s.CardNo,
        CardDci = s.CardDci,
        MccCode = s.MccCode,
        Tc = s.Tc,
        UsageCode = s.UsageCode,
        DisputeCode = s.DisputeCode,
        ControlStat = s.ControlStat,
        SourceAmount = s.SourceAmount,
        SourceCurrency = s.SourceCurrency,
        DestinationAmount = s.DestinationAmount,
        DestinationCurrency = s.DestinationCurrency,
        CashbackAmount = s.CashbackAmount,
        ReimbursementAmount = s.ReimbursementAmount,
        ReimbursementAttribute = s.ReimbursementAttribute,
        MicrofilmNumber = s.MicrofilmNumber,
        MerchantCity = s.MerchantCity,
        MerchantName = s.MerchantName,
        CardAcceptorId = s.CardAcceptorId,
        TxnDate = s.TxnDate,
        TxnTime = s.TxnTime,
        FileId = s.FileId
    };

    private static IngestionClearingMscDetail MapClearingMscDetail(ClearingMscDetail s) => new()
    {
        TxnType = s.TxnType,
        IoDate = s.IoDate,
        IoFlag = s.IoFlag,
        OceanTxnGuid = s.OceanTxnGuid,
        ClrNo = s.ClrNo,
        Rrn = s.Rrn,
        Arn = s.Arn,
        ReasonCode = s.ReasonCode,
        Reserved = s.Reserved,
        ProvisionCode = s.ProvisionCode,
        CardNo = s.CardNo,
        CardDci = s.CardDci,
        MccCode = s.MccCode,
        Mtid = s.Mtid,
        FunctionCode = s.FunctionCode,
        ProcessCode = s.ProcessCode,
        ReversalIndicator = s.ReversalIndicator,
        DisputeCode = s.DisputeCode,
        ControlStat = s.ControlStat,
        SourceAmount = s.SourceAmount,
        SourceCurrency = s.SourceCurrency,
        DestinationAmount = s.DestinationAmount,
        DestinationCurrency = s.DestinationCurrency,
        CashbackAmount = s.CashbackAmount,
        ReimbursementAmount = s.ReimbursementAmount,
        ReimbursementAttribute = s.ReimbursementAttribute,
        AncillaryTransactionCode = s.AncillaryTransactionCode,
        AncillaryTransactionAmount = s.AncillaryTransactionAmount,
        MicrofilmNumber = s.MicrofilmNumber,
        MerchantCity = s.MerchantCity,
        MerchantName = s.MerchantName,
        CardAcceptorId = s.CardAcceptorId,
        TxnDate = s.TxnDate,
        TxnTime = s.TxnTime,
        FileId = s.FileId
    };

    private static IngestionClearingBkmDetail MapClearingBkmDetail(ClearingBkmDetail s) => new()
    {
        TxnType = s.TxnType,
        IoDate = s.IoDate,
        IoFlag = s.IoFlag,
        OceanTxnGuid = s.OceanTxnGuid,
        ClrNo = s.ClrNo,
        Rrn = s.Rrn,
        Arn = s.Arn,
        ReasonCode = s.ReasonCode,
        Reserved = s.Reserved,
        ProvisionCode = s.ProvisionCode,
        CardNo = s.CardNo,
        CardDci = s.CardDci,
        MccCode = s.MccCode,
        Mtid = s.Mtid,
        FunctionCode = s.FunctionCode,
        ProcessCode = s.ProcessCode,
        DisputeCode = s.DisputeCode,
        ControlStat = s.ControlStat,
        SourceAmount = s.SourceAmount,
        SourceCurrency = s.SourceCurrency,
        DestinationAmount = s.DestinationAmount,
        DestinationCurrency = s.DestinationCurrency,
        CashbackAmount = s.CashbackAmount,
        ReimbursementAmount = s.ReimbursementAmount,
        ReimbursementAttribute = s.ReimbursementAttribute,
        MicrofilmNumber = s.MicrofilmNumber,
        MerchantCity = s.MerchantCity,
        MerchantName = s.MerchantName,
        CardAcceptorId = s.CardAcceptorId,
        TxnDate = s.TxnDate,
        TxnTime = s.TxnTime,
        FileId = s.FileId
    };
}

