IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'Transaction' AND COLUMN_NAME = 'CustomerTransactionId'
)
BEGIN
    ALTER TABLE Core.[Transaction] ADD CustomerTransactionId VARCHAR(50) NULL;
END
GO


IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'Transaction' AND COLUMN_NAME = 'IsCancelled'
)
BEGIN
    ALTER TABLE Core.[Transaction] ADD IsCancelled BIT NOT NULL DEFAULT 0;
END
GO


IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'Transaction' AND COLUMN_NAME = 'IsSettlementReceived'
)
BEGIN
    ALTER TABLE Core.[Transaction] ADD IsSettlementReceived BIT NOT NULL DEFAULT 0;
END
GO


IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'Transaction' AND COLUMN_NAME = 'PaymentChannel'
)
BEGIN
    ALTER TABLE Core.[Transaction] ADD PaymentChannel VARCHAR(300) NULL;
END
GO
