IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'Account' AND COLUMN_NAME = 'IsNameMaskingEnabled'
)
BEGIN
    ALTER TABLE Core.Account 
    ADD IsNameMaskingEnabled BIT NOT NULL DEFAULT 0;
END
