IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'Transaction' AND COLUMN_NAME = 'UsedCreditAmount'
)
BEGIN
    ALTER TABLE Core.[Transaction] ADD UsedCreditAmount NUMERIC(18,2) NOT NULL DEFAULT(0.0);
END
GO