IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core' AND TABLE_NAME = 'Wallet' AND COLUMN_NAME = 'BlockedBalanceCredit'
)
BEGIN
    ALTER TABLE Core.[Wallet] ADD BlockedBalanceCredit NUMERIC(18,2) NOT NULL DEFAULT(0.0);
END
GO