USE [PF]
GO

INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',139,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Advantage',123,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Axess',46,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',100,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',137,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',950,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',205,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',121,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',6234,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',951,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',4422,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',151,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',208,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',1,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',148,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',4,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',125,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',807,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',88,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',7730,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',5051,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',6226,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',143,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'World',135,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bonus',99,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',6002,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'World',15,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',16,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',138,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bonus',109,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',6001,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',115,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',116,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',6003,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'World',67,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',129,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',142,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',91,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',150,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bonus',124,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',6005,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',122,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',147,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bankkart Combo',10,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',17,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',132,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',108,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',6006,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',3172,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Paraf',12,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'World',203,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Maximum',64,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',9093,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bonus',206,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',9805,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'CardFinans',111,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',98,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',9876,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',7827,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',149,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',35,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',210,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',8309,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bonus',32,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',209,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',29,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',211,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bonus',134,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Axess',146,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',141,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bonus',59,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',0,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',570,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bonus',103,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',6004,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',14,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',96,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',92,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'Bonus',62,GETDATE(),N'','Active')
INSERT INTO [Card].[Loyalty]([Id],[Name],[BankCode],[CreateDate],[CreatedBy],[RecordStatus]) VALUES(NEWID(),'',997,GETDATE(),N'','Active')

GO


