// <auto-generated />
using System;
using LinkPara.Emoney.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkPara.Emoney.Infrastructure.Persistence.Migrations.PostgreSql
{
    [DbContext(typeof(EmoneyDbContext))]
    [Migration("20230711080230_UserIdRemovedFromWalletTable")]
    partial class UserIdRemovedFromWalletTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountKycLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_kyc_level");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_status");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_type");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("change_reason");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closing_date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identity_number");

                    b.Property<DateTime>("KycChangeDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("kyc_change_date");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("opening_date");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone_code");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime>("SuspendedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("suspended_date");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.ToTable("account", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.AccountCurrentLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("DailyCorporateWalletTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_corporate_wallet_transfer_amount");

                    b.Property<int>("DailyCorporateWalletTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_corporate_wallet_transfer_count");

                    b.Property<decimal>("DailyDepositAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_deposit_amount");

                    b.Property<int>("DailyDepositCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_deposit_count");

                    b.Property<decimal>("DailyInternalTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_internal_transfer_amount");

                    b.Property<int>("DailyInternalTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_internal_transfer_count");

                    b.Property<decimal>("DailyInternationalTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_international_transfer_amount");

                    b.Property<int>("DailyInternationalTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_international_transfer_count");

                    b.Property<decimal>("DailyWithdrawalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_withdrawal_amount");

                    b.Property<int>("DailyWithdrawalCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_withdrawal_count");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LevelDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("level_date");

                    b.Property<decimal>("MonthlyCorporateWalletTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_corporate_wallet_transfer_amount");

                    b.Property<int>("MonthlyCorporateWalletTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_corporate_wallet_transfer_count");

                    b.Property<decimal>("MonthlyDepositAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_deposit_amount");

                    b.Property<int>("MonthlyDepositCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_deposit_count");

                    b.Property<decimal>("MonthlyInternalTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_internal_transfer_amount");

                    b.Property<int>("MonthlyInternalTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_internal_transfer_count");

                    b.Property<decimal>("MonthlyInternationalTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_international_transfer_amount");

                    b.Property<int>("MonthlyInternationalTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_international_transfer_count");

                    b.Property<decimal>("MonthlyWithdrawalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_withdrawal_amount");

                    b.Property<int>("MonthlyWithdrawalCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_withdrawal_count");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<Guid>("TierLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("tier_level_id");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_account_current_level");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_account_current_level_currency_code");

                    b.ToTable("account_current_level", "limit");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.AccountCustomTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("account_name");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("email");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone_code");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<Guid>("TierLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("tier_level_id");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_account_custom_tier");

                    b.HasIndex("TierLevelId")
                        .HasDatabaseName("ix_account_custom_tier_tier_level_id");

                    b.ToTable("account_custom_tier", "limit");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.AccountUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone_code");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account_user");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_user_account_id");

                    b.ToTable("account_user", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasMaxLength(4001)
                        .HasColumnType("character varying(4001)")
                        .HasColumnName("private_key");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("public_key");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_api_key");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_api_key_partner_id");

                    b.HasIndex("PublicKey")
                        .HasDatabaseName("ix_api_key_public_key");

                    b.ToTable("api_key", "partner");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_bank");

                    b.HasAlternateKey("Code")
                        .HasName("ak_bank_code");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_bank_code");

                    b.ToTable("bank", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.BankLogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_id");

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_bank_logo");

                    b.HasIndex("BankId")
                        .HasDatabaseName("ix_bank_logo_bank_id");

                    b.ToTable("bank_logo", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("currency_type");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("symbol");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_currency");

                    b.HasAlternateKey("Code")
                        .HasName("ak_currency_code");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_currency_code");

                    b.ToTable("currency", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("PartnerNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("partner_number");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_partner");

                    b.HasIndex("PartnerNumber")
                        .HasDatabaseName("ix_partner_partner_number");

                    b.ToTable("partner", "partner");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.PartnerCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_partner_counter");

                    b.HasIndex("Index")
                        .HasDatabaseName("ix_partner_counter_index");

                    b.ToTable("partner_counter", "partner");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.PricingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivationDateEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("activation_date_end");

                    b.Property<DateTime>("ActivationDateStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("activation_date_start");

                    b.Property<int?>("BankCode")
                        .HasColumnType("integer")
                        .HasColumnName("bank_code");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transfer_type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_pricing_profile");

                    b.HasIndex("BankCode")
                        .HasDatabaseName("ix_pricing_profile_bank_code");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_pricing_profile_currency_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_pricing_profile_status");

                    b.HasIndex("TransferType")
                        .HasDatabaseName("ix_pricing_profile_transfer_type");

                    b.ToTable("pricing_profile", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.PricingProfileItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("fee");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_amount");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_amount");

                    b.Property<Guid>("PricingProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_profile_id");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<string>("WalletType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("wallet_type");

                    b.HasKey("Id")
                        .HasName("pk_pricing_profile_item");

                    b.HasIndex("PricingProfileId")
                        .HasDatabaseName("ix_pricing_profile_item_pricing_profile_id");

                    b.ToTable("pricing_profile_item", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Provision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("ClientIpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_ip_address");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_return");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<Guid?>("PaymentProvisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_provision_id");

                    b.Property<string>("ProvisionReference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasDefaultValue("000000000000000")
                        .HasColumnName("provision_reference");

                    b.Property<string>("ProvisionSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provision_source");

                    b.Property<string>("ProvisionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provision_status");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("return_date");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WalletNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("wallet_number");

                    b.HasKey("Id")
                        .HasName("pk_provision");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_provision_conversation_id");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_provision_partner_id");

                    b.HasIndex("PaymentProvisionId")
                        .HasDatabaseName("ix_provision_payment_provision_id");

                    b.HasIndex("ProvisionReference")
                        .HasDatabaseName("ix_provision_provision_reference");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_provision_transaction_id");

                    b.ToTable("provision", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.ReturnTransactionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("IncomingTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("incoming_transaction_id");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("MoneyTransferPaymentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("money_transfer_payment_date");

                    b.Property<Guid>("MoneyTransferReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("money_transfer_reference_id");

                    b.Property<string>("MoneyTransferStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("money_transfer_status");

                    b.Property<int>("ReceiverBankCode")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_bank_code");

                    b.Property<string>("ReceiverIbanNumber")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("receiver_iban_number");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverTaxNumber")
                        .HasColumnType("text")
                        .HasColumnName("receiver_tax_number");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TransactionBankCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("transaction_bank_code");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transfer_type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_return_transaction_request");

                    b.ToTable("return_transaction_request", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.SavedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tag");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_account");

                    b.ToTable("saved_account", "core");

                    b.HasDiscriminator<string>("Type").HasValue("SavedAccount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.TierLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("DailyMaxCorporateWalletTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_max_corporate_wallet_transfer_amount");

                    b.Property<int>("DailyMaxCorporateWalletTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_max_corporate_wallet_transfer_count");

                    b.Property<decimal>("DailyMaxDepositAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_max_deposit_amount");

                    b.Property<int>("DailyMaxDepositCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_max_deposit_count");

                    b.Property<decimal>("DailyMaxInternalTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_max_internal_transfer_amount");

                    b.Property<int>("DailyMaxInternalTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_max_internal_transfer_count");

                    b.Property<decimal>("DailyMaxInternationalTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_max_international_transfer_amount");

                    b.Property<int>("DailyMaxInternationalTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_max_international_transfer_count");

                    b.Property<decimal>("DailyMaxWithdrawalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_max_withdrawal_amount");

                    b.Property<int>("DailyMaxWithdrawalCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_max_withdrawal_count");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<decimal>("MaxBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_balance");

                    b.Property<decimal>("MaxBalanceCorporateWallet")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_balance_corporate_wallet");

                    b.Property<decimal>("MonthlyMaxCorporateWalletTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_max_corporate_wallet_transfer_amount");

                    b.Property<int>("MonthlyMaxCorporateWalletTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_max_corporate_wallet_transfer_count");

                    b.Property<decimal>("MonthlyMaxDepositAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_max_deposit_amount");

                    b.Property<int>("MonthlyMaxDepositCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_max_deposit_count");

                    b.Property<decimal>("MonthlyMaxInternalTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_max_internal_transfer_amount");

                    b.Property<int>("MonthlyMaxInternalTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_max_internal_transfer_count");

                    b.Property<decimal>("MonthlyMaxInternationalTransferAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_max_international_transfer_amount");

                    b.Property<int>("MonthlyMaxInternationalTransferCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_max_international_transfer_count");

                    b.Property<decimal>("MonthlyMaxWithdrawalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monthly_max_withdrawal_amount");

                    b.Property<int>("MonthlyMaxWithdrawalCount")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_max_withdrawal_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("TierLevelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tier_level_type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_tier_level");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_tier_level_currency_code");

                    b.ToTable("tier_level", "limit");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Channel")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("channel");

                    b.Property<Guid?>("CounterWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_wallet_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_balance");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalReferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_reference_id");

                    b.Property<DateTime?>("ExternalTransactionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("external_transaction_date");

                    b.Property<Guid?>("IncomingTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("incoming_transaction_id");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("PreBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("pre_balance");

                    b.Property<int?>("ReceiverBankCode")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_bank_code");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_transaction_id");

                    b.Property<Guid?>("ReturnedTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("returned_transaction_id");

                    b.Property<int?>("SenderBankCode")
                        .HasColumnType("integer")
                        .HasColumnName("sender_bank_code");

                    b.Property<string>("SenderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_name");

                    b.Property<string>("Tag")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tag");

                    b.Property<string>("TagTitle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag_title");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionDirection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_direction");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_status");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<Guid?>("WithdrawRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("withdraw_request_id");

                    b.HasKey("Id")
                        .HasName("pk_transaction");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_transaction_currency_code");

                    b.HasIndex("RelatedTransactionId")
                        .HasDatabaseName("ix_transaction_related_transaction_id");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("ix_transaction_transaction_date");

                    b.HasIndex("TransactionStatus")
                        .HasDatabaseName("ix_transaction_transaction_status");

                    b.HasIndex("TransactionType")
                        .HasDatabaseName("ix_transaction_transaction_type");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_transaction_wallet_id");

                    b.HasIndex("WithdrawRequestId")
                        .HasDatabaseName("ix_transaction_withdraw_request_id");

                    b.ToTable("transaction", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.TransferOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("ReceiverAccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receiver_account_type");

                    b.Property<string>("ReceiverAccountValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receiver_account_value");

                    b.Property<string>("ReceiverNameSurname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receiver_name_surname");

                    b.Property<string>("ReceiverPhoneCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("receiver_phone_code");

                    b.Property<string>("ReceiverWalletNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receiver_wallet_number");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("SenderNameSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_name_surname");

                    b.Property<string>("SenderUserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sender_user_type");

                    b.Property<string>("SenderWalletNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sender_wallet_number");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_date");

                    b.Property<string>("TransferOrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transfer_order_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer_order");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_transfer_order_currency_code");

                    b.HasIndex("SenderWalletNumber")
                        .HasDatabaseName("ix_transfer_order_sender_wallet_number");

                    b.HasIndex("TransferDate")
                        .HasDatabaseName("ix_transfer_order_transfer_date");

                    b.ToTable("transfer_order", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("account_id");

                    b.Property<decimal>("BlockedBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("blocked_balance");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closing_date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("CurrentBalanceCash")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_balance_cash");

                    b.Property<decimal>("CurrentBalanceCredit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_balance_credit");

                    b.Property<bool>("ExceededLimitsThisMonth")
                        .HasColumnType("boolean")
                        .HasColumnName("exceeded_limits_this_month");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("friendly_name");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<bool>("IsMainWallet")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main_wallet");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_activity_date");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime?>("OpeningDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("opening_date");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<string>("WalletNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("wallet_number");

                    b.Property<string>("WalletType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("wallet_type");

                    b.HasKey("Id")
                        .HasName("pk_wallet");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_wallet_account_id");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_wallet_currency_code");

                    b.HasIndex("WalletNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_wallet_wallet_number");

                    b.ToTable("wallet", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.WithdrawRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("description");

                    b.Property<Guid>("InternalTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_transaction_id");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("MoneyTransferPaymentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("money_transfer_payment_date");

                    b.Property<Guid>("MoneyTransferReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("money_transfer_reference_id");

                    b.Property<string>("MoneyTransferStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("money_transfer_status");

                    b.Property<int>("ReceiverBankCode")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_bank_code");

                    b.Property<string>("ReceiverBankName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("receiver_bank_name");

                    b.Property<string>("ReceiverIbanNumber")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("receiver_iban_number");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverTaxNumber")
                        .HasColumnType("text")
                        .HasColumnName("receiver_tax_number");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<int>("TransactionBankCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("transaction_bank_code");

                    b.Property<string>("TransactionBankName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_bank_name");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transfer_type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<string>("WalletNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("wallet_number");

                    b.Property<string>("WithdrawStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("withdraw_status");

                    b.HasKey("Id")
                        .HasName("pk_withdraw_request");

                    b.HasIndex("CreateDate")
                        .HasDatabaseName("ix_withdraw_request_create_date");

                    b.HasIndex("WalletNumber")
                        .HasDatabaseName("ix_withdraw_request_wallet_number");

                    b.HasIndex("WithdrawStatus", "RecordStatus")
                        .HasDatabaseName("ix_withdraw_request_withdraw_status_record_status");

                    b.ToTable("withdraw_request", "core");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.SavedBankAccount", b =>
                {
                    b.HasBaseType("LinkPara.Emoney.Domain.Entities.SavedAccount");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_id");

                    b.Property<string>("Iban")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("iban");

                    b.HasIndex("BankId")
                        .HasDatabaseName("ix_saved_account_bank_id");

                    b.ToTable("saved_account", "core");

                    b.HasDiscriminator().HasValue("BankAccount");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.SavedWalletAccount", b =>
                {
                    b.HasBaseType("LinkPara.Emoney.Domain.Entities.SavedAccount");

                    b.Property<string>("WalletNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("wallet_number");

                    b.Property<Guid>("WalletOwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_owner_account_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_account_user_id");

                    b.ToTable("saved_account", "core");

                    b.HasDiscriminator().HasValue("Wallet");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.AccountCurrentLevel", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_current_level_currency_currency_id");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.AccountCustomTier", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.TierLevel", "TierLevel")
                        .WithMany()
                        .HasForeignKey("TierLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_custom_tier_tier_level_tier_level_id");

                    b.Navigation("TierLevel");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.AccountUser", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Account", "Account")
                        .WithMany("AccountUsers")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_user_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_partner_partner_id");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.BankLogo", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bank_logo_bank_bank_id");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.PricingProfile", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pricing_profile_bank_bank_id");

                    b.HasOne("LinkPara.Emoney.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pricing_profile_currency_currency_id");

                    b.Navigation("Bank");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.PricingProfileItem", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.PricingProfile", "PricingProfile")
                        .WithMany("PricingProfileItems")
                        .HasForeignKey("PricingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pricing_profile_item_pricing_profile_pricing_profile_id");

                    b.Navigation("PricingProfile");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Provision", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .HasConstraintName("fk_provision_partner_partner_id");

                    b.HasOne("LinkPara.Emoney.Domain.Entities.Provision", "PaymentProvision")
                        .WithMany()
                        .HasForeignKey("PaymentProvisionId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .HasConstraintName("fk_provision_provision_payment_provision_id");

                    b.HasOne("LinkPara.Emoney.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provision_transaction_transaction_id");

                    b.Navigation("Partner");

                    b.Navigation("PaymentProvision");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.TierLevel", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tier_level_currency_currency_id");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_currency_currency_id");

                    b.HasOne("LinkPara.Emoney.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_wallet_wallet_id");

                    b.Navigation("Currency");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.TransferOrder", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_order_currency_currency_id");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Account", "Account")
                        .WithMany("Wallets")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_account_account_id");

                    b.HasOne("LinkPara.Emoney.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_currency_currency_id");

                    b.Navigation("Account");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.SavedBankAccount", b =>
                {
                    b.HasOne("LinkPara.Emoney.Domain.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_account_bank_bank_id");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Account", b =>
                {
                    b.Navigation("AccountUsers");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.PricingProfile", b =>
                {
                    b.Navigation("PricingProfileItems");
                });

            modelBuilder.Entity("LinkPara.Emoney.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
