IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'Core'
      AND TABLE_NAME = 'User'
      AND COLUMN_NAME = 'AmlReferenceNumber'
)
BEGIN
    ALTER TABLE Core.[User] ADD AmlReferenceNumber VARCHAR(150);
END