DO $$
BEGIN
CREATE TABLE IF NOT exists core.company_pool (
	id uuid NOT NULL,
	company_pool_status varchar(50) NOT NULL,
	company_type varchar(50) NOT NULL,
	title varchar(256) NOT NULL,
	email varchar(256) NOT NULL,
	phone_code varchar(15) NOT NULL,
	phone_number varchar(15) NOT NULL,
	land_phone varchar(15) NULL,
	web_site_url varchar(100) NULL,
	tax_administration varchar(200) NOT NULL,
	tax_number varchar(11) NOT NULL,
	iban varchar(26) NULL,
	postal_code varchar(5) NOT NULL,
	address varchar(256) NOT NULL,
	country int4 NOT NULL,
	country_name varchar(200) NOT NULL,
	city int4 NOT NULL,
	city_name varchar(200) NOT NULL,
	district int4 NOT NULL,
	district_name varchar(200) NOT NULL,
	authorized_person_identity_number varchar(11) NULL,
	authorized_person_name varchar(100) NOT NULL,
	authorized_person_surname varchar(100) NOT NULL,
	authorized_person_birth_date timestamp NOT NULL,
	authorized_person_company_phone_code varchar(15) NOT NULL,
	authorized_person_company_phone_number varchar(15) NOT NULL,
	reject_reason varchar(256) NULL,
	action_user uuid NOT NULL,
	action_date timestamp NOT NULL,
	channel varchar(50) NOT NULL,
	create_date timestamp NOT NULL,
	update_date timestamp NULL,
	created_by varchar(50) NOT NULL,
	last_modified_by varchar(50) NULL,
	record_status varchar(50) NOT NULL,
	mersis_number varchar(16) NULL,
	authorized_person_email varchar(256) DEFAULT ''::character varying NOT NULL,
	account_id uuid NULL,
	CONSTRAINT pk_company_pool PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_company_pool_account_id ON core.company_pool (account_id);
END $$;


DO $$
BEGIN
CREATE TABLE IF NOT exists core.bulk_transfer (
	id uuid NOT NULL,
	bulk_transfer_status varchar(50) NOT NULL,
	file_name varchar(400) NULL,
	reference_number int4 GENERATED BY DEFAULT AS IDENTITY( MINVALUE 0 NO MAXVALUE START 0 NO CYCLE) NOT NULL,
	action_user uuid NULL,
	action_date timestamp NOT NULL,
	sender_wallet_number varchar(50) NOT NULL,
	bulk_transfer_type varchar(50) NOT NULL,
	account_id uuid NOT NULL,
	create_date timestamp NOT NULL,
	update_date timestamp NULL,
	created_by varchar(50) NOT NULL,
	last_modified_by varchar(50) NULL,
	record_status varchar(50) NOT NULL,
	action_user_name varchar(150) NULL,
	CONSTRAINT pk_bulk_transfer PRIMARY KEY (id)
);
END $$;


DO $$
BEGIN
CREATE TABLE IF NOT exists  core.bulk_transfer_detail (
	id uuid NOT NULL,
	bulk_transfer_id uuid NOT NULL,
	full_name varchar(250) NOT NULL,
	amount numeric(18, 2) NOT NULL,
	currency_code varchar(10) NOT NULL,
	description varchar(400) NULL,
	receiver varchar(50) NOT NULL,
	bulk_transfer_detail_status varchar(50) NOT NULL,
	transaction_id uuid NULL,
	create_date timestamp NOT NULL,
	update_date timestamp NULL,
	created_by varchar(50) NOT NULL,
	last_modified_by varchar(50) NULL,
	record_status varchar(50) NOT NULL,
	bsmv_amount numeric DEFAULT 0.0 NOT NULL,
	commission_amount numeric DEFAULT 0.0 NOT NULL,
	exception_message varchar(400) NULL,
	CONSTRAINT pk_bulk_transfer_detail PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_bulk_transfer_detail_bulk_transfer_id ON core.bulk_transfer_detail USING btree (bulk_transfer_id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_bulk_transfer_detail_transaction_id ON core.bulk_transfer_detail USING btree (transaction_id);
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
      SELECT conname FROM pg_constraint
        WHERE conname = 'fk_company_pool_account_account_id'
    ) THEN
ALTER TABLE core.company_pool ADD CONSTRAINT fk_company_pool_account_account_id FOREIGN KEY (account_id) REFERENCES core.account(id);
END IF;
END $$;


DO $$
BEGIN
  IF NOT EXISTS (
      SELECT conname FROM pg_constraint
        WHERE conname = 'fk_bulk_transfer_detail_bulk_transfer_bulk_transfer_id'
    ) THEN

	ALTER TABLE core.bulk_transfer_detail ADD CONSTRAINT fk_bulk_transfer_detail_bulk_transfer_bulk_transfer_id FOREIGN KEY (bulk_transfer_id) REFERENCES core.bulk_transfer(id) ON DELETE CASCADE;

END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
      SELECT conname FROM pg_constraint
        WHERE conname = 'fk_bulk_transfer_detail_transaction_transaction_id'
    ) THEN
	ALTER TABLE core.bulk_transfer_detail ADD CONSTRAINT fk_bulk_transfer_detail_transaction_transaction_id FOREIGN KEY (transaction_id) REFERENCES core."transaction"(id);

END IF;
END $$;