DO $$
BEGIN
    CREATE TABLE IF NOT EXISTS core.iks_terminal (
        id uuid NOT NULL,
        merchant_id uuid NOT NULL,
        reference_code character varying(12) NOT NULL,
        global_merchant_id character varying(8) NOT NULL,
        psp_merchant_id character varying(15) NOT NULL,
        terminal_id character varying(10),
        status_code character varying(1) NOT NULL,
        type character varying(1) NOT NULL,
        brand_code character varying(1),
        model character varying(10),
        serial_no character varying(25),
        owner_psp_no integer NOT NULL,
        owner_terminal_id character varying(10),
        brand_sharing character varying(1),
        pin_pad character varying(1),
        contactless character varying(1),
        connection_type character varying(1),
        virtual_pos_url character varying(150),
        hosting_tax_no character varying(11),
        hosting_trade_name character varying(30),
        hosting_url character varying(150),
        payment_gw_tax_no character varying(11),
        payment_gw_trade_name character varying(30),
        payment_gw_url character varying(150),
        service_provider_psp_no integer NOT NULL,
        fiscal_no character varying(12),
        tech_pos integer NOT NULL,
        service_provider_psp_merchant_id character varying(15),
        pf_main_merchant_id character varying(15),
        response_code character varying(3),
        response_code_explanation character varying(2000),
        create_date timestamp without time zone NOT NULL,
        update_date timestamp without time zone,
        created_by character varying(50) NOT NULL,
        last_modified_by character varying(50),
        record_status character varying(50) NOT NULL,
        CONSTRAINT pk_iks_terminal PRIMARY KEY (id)
    );
END $$;