DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables
                       WHERE table_schema = 'core'
                         AND table_name = 'transaction_reference_counter') THEN
            CREATE TABLE core.transaction_reference_counter (
                                                                id uuid NOT NULL,
                                                                transaction_reference_int int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
                                                                transaction_reference_guid uuid NOT NULL,
                                                                create_date timestamp NOT NULL,
                                                                update_date timestamp NULL,
                                                                created_by varchar(50) NOT NULL,
                                                                last_modified_by varchar(50) NULL,
                                                                record_status varchar(50) NOT NULL,
                                                                CONSTRAINT pk_transaction_reference_counter PRIMARY KEY (id)
            );
        END IF;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_indexes
                       WHERE schemaname = 'core'
                         AND indexname = 'ix_transaction_reference_counter_transaction_reference_int') THEN
            CREATE UNIQUE INDEX ix_transaction_reference_counter_transaction_reference_int
                ON core.transaction_reference_counter USING btree (transaction_reference_int);
        END IF;
    END $$;
