// <auto-generated />
using System;
using LinkPara.Card.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkPara.Card.Infrastructure.Persistence.Migrations.PostgreSql
{
    [DbContext(typeof(CardDbContext))]
    partial class CardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.CustomerWalletCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankingCustomerNo")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("banking_customer_no");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("card_number");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_code");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WalletNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("wallet_number");

                    b.HasKey("Id")
                        .HasName("pk_customer_wallet_card");

                    b.ToTable("customer_wallet_card", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.DebitAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountBranch")
                        .HasColumnType("text")
                        .HasColumnName("account_branch");

                    b.Property<int?>("AccountCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("account_currency");

                    b.Property<string>("AccountNo")
                        .HasColumnType("text")
                        .HasColumnName("account_no");

                    b.Property<string>("AccountSuffix")
                        .HasColumnType("text")
                        .HasColumnName("account_suffix");

                    b.Property<string>("AcquirerCountryCode")
                        .HasColumnType("text")
                        .HasColumnName("acquirer_country_code");

                    b.Property<string>("AcquirerId")
                        .HasColumnType("text")
                        .HasColumnName("acquirer_id");

                    b.Property<string>("BankingCustomerNo")
                        .HasColumnType("text")
                        .HasColumnName("banking_customer_no");

                    b.Property<string>("BankingRefNo")
                        .HasColumnType("text")
                        .HasColumnName("banking_ref_no");

                    b.Property<decimal>("BillingAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("billing_amount");

                    b.Property<int>("BillingCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("billing_currency");

                    b.Property<string>("BusinesssApplicationIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("businesss_application_identifier");

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasColumnType("character(1)")
                        .HasColumnName("card_brand");

                    b.Property<string>("CardDci")
                        .IsRequired()
                        .HasColumnType("character(1)")
                        .HasColumnName("card_dci");

                    b.Property<string>("CardNo")
                        .HasColumnType("text")
                        .HasColumnName("card_no");

                    b.Property<string>("Channel")
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<long>("CorrelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("character(1)")
                        .HasColumnName("entry_type");

                    b.Property<int?>("ExpirationTime")
                        .HasColumnType("integer")
                        .HasColumnName("expiration_time");

                    b.Property<string>("Iban")
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<bool>("IsAdvice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_advice");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_return");

                    b.Property<bool>("IsSimulation")
                        .HasColumnType("boolean")
                        .HasColumnName("is_simulation");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Mcc")
                        .HasColumnType("text")
                        .HasColumnName("mcc");

                    b.Property<string>("MerchantId")
                        .HasColumnType("text")
                        .HasColumnName("merchant_id");

                    b.Property<string>("MerchantName")
                        .HasColumnType("text")
                        .HasColumnName("merchant_name");

                    b.Property<string>("NationalSwitchId")
                        .HasColumnType("text")
                        .HasColumnName("national_switch_id");

                    b.Property<long>("OceanTxnGuid")
                        .HasColumnType("bigint")
                        .HasColumnName("ocean_txn_guid");

                    b.Property<bool?>("PartialAcceptor")
                        .HasColumnType("boolean")
                        .HasColumnName("partial_acceptor");

                    b.Property<string>("ProvisionCode")
                        .HasColumnType("text")
                        .HasColumnName("provision_code");

                    b.Property<string>("QrData")
                        .HasColumnType("text")
                        .HasColumnName("qr_data");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<decimal?>("ReplacementBillingAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("replacement_billing_amount");

                    b.Property<int?>("ReplacementBillingCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("replacement_billing_currency");

                    b.Property<decimal?>("ReplacementTransactionAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("replacement_transaction_amount");

                    b.Property<int?>("ReplacementTransactionCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("replacement_transaction_currency");

                    b.Property<long>("RequestDate")
                        .HasColumnType("bigint")
                        .HasColumnName("request_date");

                    b.Property<long>("RequestTime")
                        .HasColumnType("bigint")
                        .HasColumnName("request_time");

                    b.Property<string>("RequestType")
                        .HasColumnType("text")
                        .HasColumnName("request_type");

                    b.Property<string>("Rrn")
                        .HasColumnType("text")
                        .HasColumnName("rrn");

                    b.Property<int?>("SecurityLevelIndicator")
                        .HasColumnType("integer")
                        .HasColumnName("security_level_indicator");

                    b.Property<string>("TerminalId")
                        .HasColumnType("text")
                        .HasColumnName("terminal_id");

                    b.Property<string>("TerminalType")
                        .HasColumnType("text")
                        .HasColumnName("terminal_type");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("transaction_amount");

                    b.Property<int>("TransactionCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_currency");

                    b.Property<string>("TransactionSource")
                        .IsRequired()
                        .HasColumnType("character(1)")
                        .HasColumnName("transaction_source");

                    b.Property<string>("TransactionType")
                        .HasColumnType("text")
                        .HasColumnName("transaction_type");

                    b.Property<string>("TransferInformationCardNo")
                        .HasColumnType("text")
                        .HasColumnName("transfer_information_card_no");

                    b.Property<string>("TransferInformationName")
                        .HasColumnType("text")
                        .HasColumnName("transfer_information_name");

                    b.Property<string>("TransferInformationType")
                        .HasColumnType("character(1)")
                        .HasColumnName("transfer_information_type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_debit_authorization");

                    b.HasIndex("OceanTxnGuid")
                        .HasDatabaseName("ix_debit_authorization_ocean_txn_guid");

                    b.ToTable("debit_authorization", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.FileIngestion.CardTransactionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcquirerId")
                        .HasColumnType("text")
                        .HasColumnName("acquirer_id");

                    b.Property<string>("Arn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("arn");

                    b.Property<string>("BankingTxnCode")
                        .HasColumnType("text")
                        .HasColumnName("banking_txn_code");

                    b.Property<decimal?>("BcPoint")
                        .HasColumnType("numeric")
                        .HasColumnName("bc_point");

                    b.Property<decimal?>("BcPointAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("bc_point_amount");

                    b.Property<decimal?>("BillingAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("billing_amount");

                    b.Property<string>("BillingCurrency")
                        .HasColumnType("text")
                        .HasColumnName("billing_currency");

                    b.Property<string>("BranchId")
                        .HasColumnType("text")
                        .HasColumnName("branch_id");

                    b.Property<decimal?>("CardHolderBillingAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("card_holder_billing_amount");

                    b.Property<string>("CardHolderBillingCurrency")
                        .HasColumnType("text")
                        .HasColumnName("card_holder_billing_currency");

                    b.Property<string>("CardNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("card_no");

                    b.Property<decimal?>("CashbackAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cashback_amount");

                    b.Property<decimal?>("CcPoint")
                        .HasColumnType("numeric")
                        .HasColumnName("cc_point");

                    b.Property<decimal?>("CcPointAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cc_point_amount");

                    b.Property<string>("ChannelCode")
                        .HasColumnType("text")
                        .HasColumnName("channel_code");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_key");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EndOfDayDate")
                        .HasColumnType("date")
                        .HasColumnName("end_of_day_date");

                    b.Property<string>("FinancialType")
                        .HasColumnType("text")
                        .HasColumnName("financial_type");

                    b.Property<Guid>("ImportedFileRowId")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_file_row_id");

                    b.Property<int?>("InstallCount")
                        .HasColumnType("integer")
                        .HasColumnName("install_count");

                    b.Property<int?>("InstallOrder")
                        .HasColumnType("integer")
                        .HasColumnName("install_order");

                    b.Property<string>("IsSuccessfulTxn")
                        .HasColumnType("text")
                        .HasColumnName("is_successful_txn");

                    b.Property<string>("IsTxnSettle")
                        .HasColumnType("text")
                        .HasColumnName("is_txn_settle");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("LastReconciliationExecutionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_reconciliation_execution_group_id");

                    b.Property<Guid?>("LastReconciliationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_reconciliation_run_id");

                    b.Property<decimal?>("McPoint")
                        .HasColumnType("numeric")
                        .HasColumnName("mc_point");

                    b.Property<decimal?>("McPointAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("mc_point_amount");

                    b.Property<string>("Mcc")
                        .HasColumnType("text")
                        .HasColumnName("mcc");

                    b.Property<string>("MemberRefNo")
                        .HasColumnType("text")
                        .HasColumnName("member_ref_no");

                    b.Property<string>("MerchantCity")
                        .HasColumnType("text")
                        .HasColumnName("merchant_city");

                    b.Property<string>("MerchantCountry")
                        .HasColumnType("text")
                        .HasColumnName("merchant_country");

                    b.Property<string>("MerchantId")
                        .HasColumnType("text")
                        .HasColumnName("merchant_id");

                    b.Property<string>("MerchantName")
                        .HasColumnType("text")
                        .HasColumnName("merchant_name");

                    b.Property<string>("MerchantState")
                        .HasColumnType("text")
                        .HasColumnName("merchant_state");

                    b.Property<string>("OceanMainTxnGuid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ocean_main_txn_guid");

                    b.Property<string>("OceanTxnGuid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ocean_txn_guid");

                    b.Property<string>("OperatorCode")
                        .HasColumnType("text")
                        .HasColumnName("operator_code");

                    b.Property<decimal?>("OriginalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("original_amount");

                    b.Property<string>("OriginalCurrency")
                        .HasColumnType("text")
                        .HasColumnName("original_currency");

                    b.Property<string>("Otc")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("otc");

                    b.Property<string>("Ots")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ots");

                    b.Property<string>("PointType")
                        .HasColumnType("text")
                        .HasColumnName("point_type");

                    b.Property<string>("ProvisionCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provision_code");

                    b.Property<string>("ReconciliationState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reconciliation_state");

                    b.Property<string>("ReconciliationStateReason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reconciliation_state_reason");

                    b.Property<DateTime?>("ReconciliationStateUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reconciliation_state_updated_at");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("text")
                        .HasColumnName("response_code");

                    b.Property<string>("Rrn")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("rrn");

                    b.Property<string>("SecurityLevelIndicator")
                        .HasColumnType("text")
                        .HasColumnName("security_level_indicator");

                    b.Property<decimal?>("SettlementAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("settlement_amount");

                    b.Property<string>("SettlementCurrency")
                        .HasColumnType("text")
                        .HasColumnName("settlement_currency");

                    b.Property<string>("Stan")
                        .HasColumnType("text")
                        .HasColumnName("stan");

                    b.Property<decimal?>("SurchargeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("surcharge_amount");

                    b.Property<decimal?>("Tax1")
                        .HasColumnType("numeric")
                        .HasColumnName("tax1");

                    b.Property<decimal?>("Tax2")
                        .HasColumnType("numeric")
                        .HasColumnName("tax2");

                    b.Property<string>("TerminalId")
                        .HasColumnType("text")
                        .HasColumnName("terminal_id");

                    b.Property<string>("TerminalType")
                        .HasColumnType("text")
                        .HasColumnName("terminal_type");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<TimeOnly?>("TransactionTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("transaction_time");

                    b.Property<string>("TxnDescription")
                        .HasColumnType("text")
                        .HasColumnName("txn_description");

                    b.Property<string>("TxnEffect")
                        .HasColumnType("text")
                        .HasColumnName("txn_effect");

                    b.Property<string>("TxnInstallType")
                        .HasColumnType("text")
                        .HasColumnName("txn_install_type");

                    b.Property<int?>("TxnOrigin")
                        .HasColumnType("integer")
                        .HasColumnName("txn_origin");

                    b.Property<string>("TxnRegion")
                        .HasColumnType("text")
                        .HasColumnName("txn_region");

                    b.Property<string>("TxnSource")
                        .HasColumnType("text")
                        .HasColumnName("txn_source");

                    b.Property<string>("TxnStat")
                        .HasColumnType("text")
                        .HasColumnName("txn_stat");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("Id")
                        .HasName("pk_card_transaction_records");

                    b.HasIndex("CorrelationKey")
                        .HasDatabaseName("ix_card_transaction_records_correlation_key");

                    b.HasIndex("ImportedFileRowId")
                        .IsUnique()
                        .HasDatabaseName("ix_card_transaction_records_imported_file_row_id");

                    b.HasIndex("LastReconciliationExecutionGroupId")
                        .HasDatabaseName("ix_card_transaction_records_last_reconciliation_execution_grou");

                    b.HasIndex("OceanTxnGuid")
                        .HasDatabaseName("ix_card_transaction_records_ocean_txn_guid");

                    b.HasIndex("ReconciliationState", "ReconciliationStateUpdatedAt")
                        .HasDatabaseName("ix_card_transaction_records_reconciliation_state_reconciliatio");

                    b.HasIndex("CardNo", "Otc", "Ots", "CardHolderBillingAmount")
                        .HasDatabaseName("ix_card_transaction_records_card_no_otc_ots_card_holder_billin");

                    b.ToTable("card_transaction_records", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.FileIngestion.ClearingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AncillaryTransactionAmount")
                        .HasColumnType("text")
                        .HasColumnName("ancillary_transaction_amount");

                    b.Property<string>("AncillaryTransactionCode")
                        .HasColumnType("text")
                        .HasColumnName("ancillary_transaction_code");

                    b.Property<string>("Arn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("arn");

                    b.Property<string>("CardAcceptorId")
                        .HasColumnType("text")
                        .HasColumnName("card_acceptor_id");

                    b.Property<string>("CardDci")
                        .HasColumnType("text")
                        .HasColumnName("card_dci");

                    b.Property<string>("CardNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("card_no");

                    b.Property<decimal?>("CashbackAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cashback_amount");

                    b.Property<string>("ClrNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("clr_no");

                    b.Property<string>("ControlStat")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("control_stat");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_key");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("DestinationAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("destination_amount");

                    b.Property<string>("DestinationCurrency")
                        .HasColumnType("text")
                        .HasColumnName("destination_currency");

                    b.Property<string>("DisputeCode")
                        .HasColumnType("text")
                        .HasColumnName("dispute_code");

                    b.Property<string>("FileId")
                        .HasColumnType("text")
                        .HasColumnName("file_id");

                    b.Property<string>("FunctionCode")
                        .HasColumnType("text")
                        .HasColumnName("function_code");

                    b.Property<Guid>("ImportedFileRowId")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_file_row_id");

                    b.Property<DateOnly?>("IoDate")
                        .HasColumnType("date")
                        .HasColumnName("io_date");

                    b.Property<string>("IoFlag")
                        .HasColumnType("text")
                        .HasColumnName("io_flag");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("MccCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("mcc_code");

                    b.Property<string>("MerchantCity")
                        .HasColumnType("text")
                        .HasColumnName("merchant_city");

                    b.Property<string>("MerchantName")
                        .HasColumnType("text")
                        .HasColumnName("merchant_name");

                    b.Property<string>("MicrofilmNumber")
                        .HasColumnType("text")
                        .HasColumnName("microfilm_number");

                    b.Property<string>("Mtid")
                        .HasColumnType("text")
                        .HasColumnName("mtid");

                    b.Property<string>("OceanTxnGuid")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ocean_txn_guid");

                    b.Property<string>("ProcessCode")
                        .HasColumnType("text")
                        .HasColumnName("process_code");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProvisionCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provision_code");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<decimal?>("ReimbursementAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("reimbursement_amount");

                    b.Property<string>("ReimbursementAttribute")
                        .HasColumnType("text")
                        .HasColumnName("reimbursement_attribute");

                    b.Property<string>("Reserved")
                        .HasColumnType("text")
                        .HasColumnName("reserved");

                    b.Property<string>("ReversalIndicator")
                        .HasColumnType("text")
                        .HasColumnName("reversal_indicator");

                    b.Property<string>("Rrn")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("rrn");

                    b.Property<decimal?>("SourceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("source_amount");

                    b.Property<string>("SourceCurrency")
                        .HasColumnType("text")
                        .HasColumnName("source_currency");

                    b.Property<string>("Tc")
                        .HasColumnType("text")
                        .HasColumnName("tc");

                    b.Property<DateOnly?>("TxnDate")
                        .HasColumnType("date")
                        .HasColumnName("txn_date");

                    b.Property<TimeOnly?>("TxnTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("txn_time");

                    b.Property<string>("TxnType")
                        .HasColumnType("text")
                        .HasColumnName("txn_type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<string>("UsageCode")
                        .HasColumnType("text")
                        .HasColumnName("usage_code");

                    b.HasKey("Id")
                        .HasName("pk_clearing_records");

                    b.HasIndex("CorrelationKey")
                        .HasDatabaseName("ix_clearing_records_correlation_key");

                    b.HasIndex("ImportedFileRowId")
                        .IsUnique()
                        .HasDatabaseName("ix_clearing_records_imported_file_row_id");

                    b.HasIndex("CorrelationKey", "CreateDate")
                        .HasDatabaseName("ix_clearing_records_correlation_key_create_date");

                    b.HasIndex("ClrNo", "ControlStat", "Provider")
                        .HasDatabaseName("ix_clearing_records_clr_no_control_stat_provider");

                    b.HasIndex("ControlStat", "CardNo", "CreateDate")
                        .HasDatabaseName("ix_clearing_records_control_stat_card_no_create_date");

                    b.HasIndex("Rrn", "Arn", "ProvisionCode", "MccCode", "SourceAmount", "SourceCurrency")
                        .HasDatabaseName("ix_clearing_records_rrn_arn_provision_code_mcc_code_source_amo");

                    b.ToTable("clearing_records", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.FileIngestion.ImportedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("DeclaredFileDate")
                        .HasColumnType("text")
                        .HasColumnName("declared_file_date");

                    b.Property<string>("DeclaredFileNo")
                        .HasColumnType("text")
                        .HasColumnName("declared_file_no");

                    b.Property<string>("DeclaredFileVersionNumber")
                        .HasColumnType("text")
                        .HasColumnName("declared_file_version_number");

                    b.Property<string>("DeclaredTxnCount")
                        .HasColumnType("text")
                        .HasColumnName("declared_txn_count");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("FileFamily")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_family");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FooterCode")
                        .HasColumnType("text")
                        .HasColumnName("footer_code");

                    b.Property<string>("HeaderCode")
                        .HasColumnType("text")
                        .HasColumnName("header_code");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_path");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalLineCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_line_count");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_imported_files");

                    b.HasIndex("FileHash")
                        .IsUnique()
                        .HasDatabaseName("ix_imported_files_file_hash");

                    b.HasIndex("FileFamily", "FileName", "SourceType")
                        .HasDatabaseName("ix_imported_files_file_family_file_name_source_type");

                    b.HasIndex("FileFamily", "SourceType", "DeclaredFileDate", "DeclaredFileNo", "DeclaredFileVersionNumber")
                        .HasDatabaseName("ix_imported_files_file_family_source_type_declared_file_date_d");

                    b.ToTable("imported_files", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.FileIngestion.ImportedFileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ImportedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_file_id");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<string>("ParsedJson")
                        .HasColumnType("text")
                        .HasColumnName("parsed_json");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_line");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("RowType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("row_type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_imported_file_rows");

                    b.HasIndex("ImportedFileId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_imported_file_rows_imported_file_id_line_no");

                    b.ToTable("imported_file_rows", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.ProcessExecutionLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("acquired_at");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_type");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LockName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lock_name");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_id");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_process_execution_lock");

                    b.HasIndex("AcquiredAt")
                        .HasDatabaseName("ix_process_execution_lock_acquired_at");

                    b.HasIndex("LockName", "Status", "ExpiresAt")
                        .HasDatabaseName("ix_process_execution_lock_lock_name_status_expires_at");

                    b.ToTable("process_execution_lock", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardTransactionRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_transaction_record_id");

                    b.Property<Guid?>("ClearingRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("clearing_record_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("DecisionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("decision_code");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decision_reason");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision_type");

                    b.Property<Guid>("ExecutionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_group_id");

                    b.Property<bool>("HasClearing")
                        .HasColumnType("boolean")
                        .HasColumnName("has_clearing");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PlannedOperationCodes")
                        .HasColumnType("text")
                        .HasColumnName("planned_operation_codes");

                    b.Property<int>("PlannedOperationCount")
                        .HasColumnType("integer")
                        .HasColumnName("planned_operation_count");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_reconciliation_evaluations");

                    b.HasIndex("CardTransactionRecordId")
                        .HasDatabaseName("ix_reconciliation_evaluations_card_transaction_record_id");

                    b.HasIndex("ClearingRecordId")
                        .HasDatabaseName("ix_reconciliation_evaluations_clearing_record_id");

                    b.HasIndex("ExecutionGroupId")
                        .HasDatabaseName("ix_reconciliation_evaluations_execution_group_id");

                    b.HasIndex("DecisionType", "CreateDate")
                        .HasDatabaseName("ix_reconciliation_evaluations_decision_type_create_date");

                    b.ToTable("reconciliation_evaluations", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationManualReviewItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ExecutionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_group_id");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("ReconciliationOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_operation_id");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_note");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("review_status");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reviewed_by");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_reconciliation_manual_review_items");

                    b.HasIndex("ExecutionGroupId")
                        .HasDatabaseName("ix_reconciliation_manual_review_items_execution_group_id");

                    b.HasIndex("ReconciliationOperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_reconciliation_manual_review_items_reconciliation_operation");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_reconciliation_manual_review_items_run_id");

                    b.HasIndex("ReviewStatus", "CreateDate")
                        .HasDatabaseName("ix_reconciliation_manual_review_items_review_status_create_date");

                    b.ToTable("reconciliation_manual_review_items", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardTransactionRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_transaction_record_id");

                    b.Property<Guid?>("ClearingRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("clearing_record_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<int?>("DependsOnIndex")
                        .HasColumnType("integer")
                        .HasColumnName("depends_on_index");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_text");

                    b.Property<Guid>("ExecutionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_group_id");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsApprovalGate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approval_gate");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation_code");

                    b.Property<int>("OperationIndex")
                        .HasColumnType("integer")
                        .HasColumnName("operation_index");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_reconciliation_operations");

                    b.HasIndex("ClearingRecordId")
                        .HasDatabaseName("ix_reconciliation_operations_clearing_record_id");

                    b.HasIndex("ExecutionGroupId")
                        .HasDatabaseName("ix_reconciliation_operations_execution_group_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_reconciliation_operations_idempotency_key");

                    b.HasIndex("CardTransactionRecordId", "CreateDate")
                        .HasDatabaseName("ix_reconciliation_operations_card_transaction_record_id_create");

                    b.HasIndex("CardTransactionRecordId", "RunId")
                        .HasDatabaseName("ix_reconciliation_operations_card_transaction_record_id_run_id");

                    b.HasIndex("RunId", "OperationIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_reconciliation_operations_run_id_operation_index");

                    b.HasIndex("Mode", "Status", "CreateDate")
                        .HasDatabaseName("ix_reconciliation_operations_mode_status_create_date");

                    b.ToTable("reconciliation_operations", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationOperationExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_no");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_text");

                    b.Property<Guid>("ExecutionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_group_id");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("ReconciliationOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_operation_id");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text")
                        .HasColumnName("response_payload");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_reconciliation_operation_executions");

                    b.HasIndex("ExecutionGroupId")
                        .HasDatabaseName("ix_reconciliation_operation_executions_execution_group_id");

                    b.HasIndex("ReconciliationOperationId")
                        .HasDatabaseName("ix_reconciliation_operation_executions_reconciliation_operatio");

                    b.HasIndex("Outcome", "CreateDate")
                        .HasDatabaseName("ix_reconciliation_operation_executions_outcome_create_date");

                    b.HasIndex("ReconciliationOperationId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("ix_reconciliation_operation_executions_reconciliation_operatio1");

                    b.ToTable("reconciliation_operation_executions", "core");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.FileIngestion.CardTransactionRecord", b =>
                {
                    b.HasOne("LinkPara.Card.Domain.Entities.FileIngestion.ImportedFileRow", "ImportedFileRow")
                        .WithOne("CardTransactionRecord")
                        .HasForeignKey("LinkPara.Card.Domain.Entities.FileIngestion.CardTransactionRecord", "ImportedFileRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_transaction_records_imported_file_rows_imported_file_r");

                    b.Navigation("ImportedFileRow");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.FileIngestion.ClearingRecord", b =>
                {
                    b.HasOne("LinkPara.Card.Domain.Entities.FileIngestion.ImportedFileRow", "ImportedFileRow")
                        .WithOne("ClearingRecord")
                        .HasForeignKey("LinkPara.Card.Domain.Entities.FileIngestion.ClearingRecord", "ImportedFileRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clearing_records_imported_file_rows_imported_file_row_id");

                    b.Navigation("ImportedFileRow");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.FileIngestion.ImportedFileRow", b =>
                {
                    b.HasOne("LinkPara.Card.Domain.Entities.FileIngestion.ImportedFile", "ImportedFile")
                        .WithMany("Rows")
                        .HasForeignKey("ImportedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imported_file_rows_imported_files_imported_file_id");

                    b.Navigation("ImportedFile");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationEvaluation", b =>
                {
                    b.HasOne("LinkPara.Card.Domain.Entities.FileIngestion.CardTransactionRecord", null)
                        .WithMany()
                        .HasForeignKey("CardTransactionRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reconciliation_evaluations_card_transaction_records_card_tr");

                    b.HasOne("LinkPara.Card.Domain.Entities.FileIngestion.ClearingRecord", null)
                        .WithMany()
                        .HasForeignKey("ClearingRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reconciliation_evaluations_clearing_records_clearing_record");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationManualReviewItem", b =>
                {
                    b.HasOne("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationOperation", "ReconciliationOperation")
                        .WithMany()
                        .HasForeignKey("ReconciliationOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reconciliation_manual_review_items_reconciliation_operation");

                    b.Navigation("ReconciliationOperation");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationOperation", b =>
                {
                    b.HasOne("LinkPara.Card.Domain.Entities.FileIngestion.CardTransactionRecord", null)
                        .WithMany()
                        .HasForeignKey("CardTransactionRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reconciliation_operations_card_transaction_records_card_tra");

                    b.HasOne("LinkPara.Card.Domain.Entities.FileIngestion.ClearingRecord", null)
                        .WithMany()
                        .HasForeignKey("ClearingRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reconciliation_operations_clearing_records_clearing_record_");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationOperationExecution", b =>
                {
                    b.HasOne("LinkPara.Card.Domain.Entities.Reconciliation.ReconciliationOperation", "ReconciliationOperation")
                        .WithMany()
                        .HasForeignKey("ReconciliationOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reconciliation_operation_executions_reconciliation_operatio");

                    b.Navigation("ReconciliationOperation");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.FileIngestion.ImportedFile", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("LinkPara.Card.Domain.Entities.FileIngestion.ImportedFileRow", b =>
                {
                    b.Navigation("CardTransactionRecord");

                    b.Navigation("ClearingRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
