//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkPara.SoftOtp.API.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions_tr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions_tr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LinkPara.SoftOtp.API.Resources.Exceptions_tr", typeof(Exceptions_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string StartOneTouchTransactionException {
            get {
                return ResourceManager.GetString("StartOneTouchTransactionException", resourceCulture);
            }
        }
        
        internal static string StartClientTransactionException {
            get {
                return ResourceManager.GetString("StartClientTransactionException", resourceCulture);
            }
        }
        
        internal static string OtpActivationFailedException {
            get {
                return ResourceManager.GetString("OtpActivationFailedException", resourceCulture);
            }
        }
        
        internal static string CheckTransactionApprovalException {
            get {
                return ResourceManager.GetString("CheckTransactionApprovalException", resourceCulture);
            }
        }
        
        internal static string VerifyLoginFailedException {
            get {
                return ResourceManager.GetString("VerifyLoginFailedException", resourceCulture);
            }
        }
    }
}
