// <auto-generated />
using System;
using LinkPara.IKS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkPara.IKS.Infrastructure.Persistence.Migrations.PostgreSql
{
    [DbContext(typeof(IKSDbContext))]
    [Migration("20251231124335_EditHostingTradeNameCharacter")]
    partial class EditHostingTradeNameCharacter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkPara.IKS.Domain.Entities.IKSTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("RequestDetails")
                        .HasColumnType("text")
                        .HasColumnName("request_details");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("response_code");

                    b.Property<string>("ResponseDetails")
                        .HasColumnType("text")
                        .HasColumnName("response_details");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_iks_transaction");

                    b.ToTable("iks_transaction", "core");
                });

            modelBuilder.Entity("LinkPara.IKS.Domain.Entities.IksTerminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrandCode")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("brand_code");

                    b.Property<string>("BrandSharing")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("brand_sharing");

                    b.Property<string>("ConnectionType")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("connection_type");

                    b.Property<string>("Contactless")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("contactless");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedNameBy")
                        .HasColumnType("text")
                        .HasColumnName("created_name_by");

                    b.Property<string>("FiscalNo")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("fiscal_no");

                    b.Property<string>("GlobalMerchantId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("global_merchant_id");

                    b.Property<string>("HostingTaxNo")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("hosting_tax_no");

                    b.Property<string>("HostingTradeName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("hosting_trade_name");

                    b.Property<string>("HostingUrl")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("hosting_url");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Model")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("model");

                    b.Property<int>("OwnerPspNo")
                        .HasColumnType("integer")
                        .HasColumnName("owner_psp_no");

                    b.Property<string>("OwnerTerminalId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_terminal_id");

                    b.Property<string>("PaymentGwTaxNo")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("payment_gw_tax_no");

                    b.Property<string>("PaymentGwTradeName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_gw_trade_name");

                    b.Property<string>("PaymentGwUrl")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("payment_gw_url");

                    b.Property<string>("PfMainMerchantId")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("pf_main_merchant_id");

                    b.Property<string>("PinPad")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("pin_pad");

                    b.Property<string>("PspMerchantId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("psp_merchant_id");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("reference_code");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("response_code");

                    b.Property<string>("ResponseCodeExplanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("response_code_explanation");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("serial_no");

                    b.Property<string>("ServiceProviderPspMerchantId")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("service_provider_psp_merchant_id");

                    b.Property<int>("ServiceProviderPspNo")
                        .HasColumnType("integer")
                        .HasColumnName("service_provider_psp_no");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("status_code");

                    b.Property<int>("TechPos")
                        .HasColumnType("integer")
                        .HasColumnName("tech_pos");

                    b.Property<string>("TerminalId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("terminal_id");

                    b.Property<string>("TerminalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("terminal_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<string>("VirtualPosUrl")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("virtual_pos_url");

                    b.Property<Guid>("VposId")
                        .HasColumnType("uuid")
                        .HasColumnName("vpos_id");

                    b.HasKey("Id")
                        .HasName("pk_iks_terminal");

                    b.ToTable("iks_terminal", "core");
                });

            modelBuilder.Entity("LinkPara.IKS.Domain.Entities.IksTerminalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangedField")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_field");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("NewData")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("new_data");

                    b.Property<string>("OldData")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("old_data");

                    b.Property<DateTime>("QueryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("query_date");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("reference_code");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("response_code");

                    b.Property<string>("ResponseCodeExplanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("response_code_explanation");

                    b.Property<string>("TerminalRecordType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("terminal_record_type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.Property<Guid>("VposId")
                        .HasColumnType("uuid")
                        .HasColumnName("vpos_id");

                    b.HasKey("Id")
                        .HasName("pk_iks_terminal_history");

                    b.ToTable("iks_terminal_history", "core");
                });

            modelBuilder.Entity("LinkPara.IKS.Domain.Entities.TimeoutIKSTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_status");

                    b.Property<string>("RequestDetails")
                        .HasColumnType("text")
                        .HasColumnName("request_details");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("response_code");

                    b.Property<string>("ResponseDetails")
                        .HasColumnType("text")
                        .HasColumnName("response_details");

                    b.Property<string>("TimeoutReturnDetails")
                        .HasColumnType("text")
                        .HasColumnName("timeout_return_details");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_timeout_iks_transaction");

                    b.ToTable("timeout_iks_transaction", "core");
                });
#pragma warning restore 612, 618
        }
    }
}
