//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkPara.Emoney.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReceiptTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiptTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkPara.Emoney.API.Resources.ReceiptTexts", typeof(ReceiptTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura ödeme.
        /// </summary>
        public static string BILLING {
            get {
                return ResourceManager.GetString("BILLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashback ödemesi.
        /// </summary>
        public static string CASHBACK {
            get {
                return ResourceManager.GetString("CASHBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart ile para yükleme.
        /// </summary>
        public static string CREDIT_CARD_IN {
            get {
                return ResourceManager.GetString("CREDIT-CARD-IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart harcaması.
        /// </summary>
        public static string CREDIT_CARD_OUT {
            get {
                return ResourceManager.GetString("CREDIT-CARD-OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cüzdanlar arası transfer.
        /// </summary>
        public static string EMONEY_IN {
            get {
                return ResourceManager.GetString("EMONEY-IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cüzdanlar arası transfer.
        /// </summary>
        public static string EMONEY_OUT {
            get {
                return ResourceManager.GetString("EMONEY-OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijital Kod Alımı.
        /// </summary>
        public static string EPIN {
            get {
                return ResourceManager.GetString("EPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finansal bakım.
        /// </summary>
        public static string MAINTENANCE {
            get {
                return ResourceManager.GetString("MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart ile bakiye yükleme.
        /// </summary>
        public static string PREPAID_CARD_IN {
            get {
                return ResourceManager.GetString("PREPAID-CARD-IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart harcaması.
        /// </summary>
        public static string PREPAID_CARD_OUT {
            get {
                return ResourceManager.GetString("PREPAID-CARD-OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İade.
        /// </summary>
        public static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İade.
        /// </summary>
        public static string RETURN_CREDIT_CARD {
            get {
                return ResourceManager.GetString("RETURN-CREDIT-CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN ile para yükleme.
        /// </summary>
        public static string TRANSFER_MONEY_IN {
            get {
                return ResourceManager.GetString("TRANSFER-MONEY-IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN&apos;a Para Gönderme.
        /// </summary>
        public static string TRANSFER_MONEY_OUT {
            get {
                return ResourceManager.GetString("TRANSFER-MONEY-OUT", resourceCulture);
            }
        }
    }
}
